### ISSUE TITLE
Add UDP port for syslog

### ISSUE THREAD

**Issue by aleksz** [deviantony/fig-elk#4]
Would it be an option?

**Comment by deviantony** [comment]
What would you like to do?

**Comment by aleksz** [comment]
Syslog input with UDP instead of TCP
25 февр. 2015 г. 8:29 пользователь "Anthony Lapenna" <
notifications@github.com> написал:

**Comment by deviantony** [comment]
Oh you're talking about the logstash configuration?

Thing is, the configuration is dynamic, the container will load the configuration present in the logstash-conf folder upon execution so all you need to do is change the input filter yourself :)

**Comment by aleksz** [comment]
Mmm, I think you also need to expose UDP port in container. Currently there
is only TCP.
25 февр. 2015 г. 10:13 пользователь "Anthony Lapenna" <
notifications@github.com> написал:

**Comment by deviantony** [comment]
You could update the exposed port in the fig.yml to:

````
 ports:
    - "5000:5000/udp"
````

Not sure if it works though.

**Comment by deviantony** [comment]
Did you manage to solve your problem?

**Comment by deviantony** [comment]
No news, I'm closing the issue.
