### ISSUE TITLE
logstash-forwarder support

### ISSUE THREAD

**Issue by dkirrane** [deviantony/fig-elk#5]
It would be nice if you could add logstash-forwarder support.
I believe this requires SSL. But not sure how to set this up??

**Comment by deviantony** [comment]
In fact, the logstash part of this solution is dynamic. You can update/replace the existing logstash configuration, restart the stack and it will be loaded.

So you just have to generate a SSL certificate, setup logstash-forwarder on a node and configure logstash with the lumberjack input.

See this article for more information: https://deviantony.wordpress.com/2014/05/19/centralized-logging-with-an-elk-stack-elasticsearch-logback-kibana/

Do not hesitate to ask any questions, I'll be glad to help.

**Comment by deviantony** [comment]
@dkirrane I'm closing the issue, do no hesitate to re-open it if you got any questions.
