### ISSUE TITLE
Default centos|redhat selinux policies prevent proper start-up

### ISSUE THREAD

**Issue by cdituri** [deviantony/fig-elk#6]
Worth adding something to the README.md that selinux must either be in permissive mode or the correct contexts must be applied for `fig-elk` to start up properly with `docker-compose up`.

I've simply set selinux as permissive to address my needs for now but if I apply actual selinux contexts to fix the problem properly I'll open a pull-request and close this issue.

**Comment by deviantony** [comment]
As said in gitter, I would love a PR for this as I've never played with Centos/Redhat.

**Comment by cdituri** [comment]
No problem - see #7
